version: '3.4'

services:
  reverse-proxy:
    image: traefik:v2.2
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/traefik.yml:/etc/traefik/traefik.yml
      - /traefik/acme.json:/acme.json