version: '3.4'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Alaska2017"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Alaska2017' -Q 'select 1'
