version: '2.1'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    ports:
      - "5601:5601"
    links:
      - elastic
    networks:
      - elk
    depends_on:
      - elastic
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elastic:9200
networks:
  elk:
    driver: bridge
