version: '2.1'
services:
  my-registry:
    image: registry:latest
    container_name: my-registry
    volumes:
      - registry:/var/lib/registry
    ports:
      - "50000:5000"
    restart: unless-stopped

  my-registry-ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 50001:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://my-registry:5000
    depends_on:
      - my-registry
volumes:
  registry:
